spring:
  application:
    name: file-sharing-app-backend

  datasource:
    url: jdbc:mysql://localhost:3306/edu_share_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /
