spring:
  application:
    name: file-sharing-app-backend

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/edu_share_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  gcp:
    storage:
      credentials:
        credentialsPath: data-oasis-457605-k8-90a116324e58.json
    bucket:
      name: edushare-files

server:
  port: 8080
  servlet:
    context-path: /
