spring:
  application:
    name: file-sharing-app-backend

  datasource:
    url: jdbc:mysql://localhost:3306/edu_share_db
    username: root
    password: userAdmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  gcp:
    storage:
      credentials:
        credentialsPath: data-oasis-457605-k8-90a116324e58.json
    bucket:
      name: edushare-files

server:
  port: 8081
  servlet:
    context-path: /
